export enum JavaType {
  'tinyint' = 'Integer',
  'smallint' = 'Integer',
  'mediumint' = 'Integer',
  'int' = 'Integer',
  'bigint' = 'Long',
  'float' = 'Double',
  'double' = 'Double',
  'decimal' = 'BigDecimal',
  'date' = 'Date',
  'time' = 'Time',
  'year' = 'Integer',
  'datetime' = 'Date',
  'timestamp' = 'Long',
  'char' = 'String',
  'varchar(256)' = 'String',
  'tinytext' = 'String',
  'text' = 'String',
  'mediumtext' = 'String',
  'longtext' = 'String',
  'tinyblob' = 'String',
  'blob' = 'String',
  'mediumblob' = 'String',
  'longblob' = 'String',
  'binary' = 'String',
  'varbinary' = 'String',
}

export enum TypeScriptType {
  'tinyint' = 'number',
  'smallint' = 'number',
  'mediumint' = 'number',
  'int' = 'number',
  'bigint' = 'number',
  'float' = 'number',
  'double' = 'number',
  'decimal' = 'number',
  'date' = 'Date',
  'time' = 'Date',
  'year' = 'number',
  'datetime' = 'Date',
  'timestamp' = 'number',
  'char(256)' = 'string',
  'varchar(256)' = 'string',
  'tinytext' = 'string',
  'text' = 'string',
  'mediumtext' = 'string',
  'longtext' = 'string',
  'tinyblob' = 'string',
  'blob' = 'string',
  'mediumblob' = 'string',
  'longblob' = 'string',
  'binary' = 'string',
  'varbinary' = 'string',
}
