export enum MockParamsType {
  '人名' = 'NAME',
  '城市' = 'CITY',
  '邮箱' = 'EMAIL',
  'URL' = 'URL',
  'IPV4' = 'IPV4',
  '整数' = 'INTEGER',
  '小数' = 'DECIMAL',
  '日期' = 'DATE',
  '手机号' = 'PHONE',
  '字符串' = 'STRING',
  '车辆' = 'VEHICLE',
  '鱼' = 'FASH',
  '昆虫' = 'INSECT',
}
